### ISSUE TITLE
Channel inactive after being idle for some time

### ISSUE THREAD

**Issue by danslapman** [traneio/ndbc#15]
Not sure if this issue shpuld be posted here or to quill, anyway, after being idle for a while (can't tell precise time, but definitly more than 6 hours) application constantly get IllegalStateException

Here is full stacktrace:
```
ava.lang.IllegalStateException: Channel inactive.
	at io.trane.ndbc.netty4.NettyChannel.channelInactive(NettyChannel.java:96)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.handler.flow.FlowControlHandler.channelInactive(FlowControlHandler.java:124)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:377)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1429)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:947)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.uti...
```

I'm using ndbc-postgres 0.1.3 via quill-ndbc-postgres 3.5.0

**Comment by juliano** [comment]
@danslapman, according to @fwbrasil in our [quill gitter channel](https://gitter.im/getquill/quill):

> ndbc doesn’t validade connections by default. I made that decision since, in high scale systems, connection validation sometimes isn’t beneficial. It possible to enable it with the config poolValidationIntervalSeconds

Can you add that configuration and test again?

**Comment by danslapman** [comment]
I will try it tomorrow and report back

**Comment by danslapman** [comment]
I confirm it works with `poolValidationIntervalSeconds = 5`

**Comment by mdedetrich** [comment]
@juliano Should we add an issue on ndbc to set the `poolValidationIntervalSeconds`  to a default  value of lets say 5? We discussed this on gitter and it makes sense to have a default configuration that errs on the side of correctness.

**Comment by juliano** [comment]
@mdedetrich absolutely. I am opening the issue.
